### ISSUE TITLE
masterha_check_repl 0.58 work with mariadb-5.5.56 causes error

### ISSUE THREAD

**Issue by Ark-Ling** [yoshinorim/mha4mysql-manager#105]
Hi,
we are running on CentOS7.4,
DataBase is Mariadb5.5.56,
when I run masterha_check_repl script,
get error in follows:

Checking if super_read_only is defined and turned on..DBD::mysql::st execute failed: Unknown system variable 'super_read_only' at /usr/share/perl5/vendor_perl/MHA/SlaveUtil.pm line 245.
Fri May  4 13:05:38 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln208] Slaves settings check failed!
Fri May  4 13:05:38 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln416] Slave configuration failed.
Fri May  4 13:05:38 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln427] Error happened on checking configurations.  at /usr/bin/masterha_check_repl line 48.
Fri May  4 13:05:38 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln525] Error happened on monitoring servers.
Fri May  4 13:05:38 2018 - [info] Got exit code 1 (Not master dead).

I'd appreciate some help.

**Comment by nyxneuf** [comment]
mariadb-10.2.14 
run masterha_check_repl script

Tue May 15 17:22:08 2018 - [info]   Connecting to root@192.168.30.74(192.168.30.74:22).. 
  Checking slave recovery environment settings..
    Opening /app/mariadb/log/relay-log.info ... ok.
    Relay log found at /app/mariadb/log, up to relay-log.000002
    Temporary relay log file is /app/mariadb/log/relay-log.000002
    Checking if super_read_only is defined and turned on..DBD::mysql::st execute failed: Unknown system variable 'super_read_only' at /usr/share/perl5/vendor_perl/MHA/SlaveUtil.pm line 245.
Tue May 15 17:22:09 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln208] Slaves settings check failed!
Tue May 15 17:22:09 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln416] Slave configuration failed.
Tue May 15 17:22:09 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln427] Error happened on checking configurations.  at /usr/bin/masterha_check_repl line 48.
Tue May 15 17:22:09 2018 - [error][/usr/share/perl5/vendor_perl/MHA/MasterMonitor.pm, ln525] Error happened on monitoring servers.
Tue May 15 17:22:09 2018 - [info] Got exit code 1 (Not master dead).

MySQL Replication Health is NOT OK!

**Comment by Ark-Ling** [comment]
as a result，I use masterha_check_repl 0.56 instead of 0.58，resolve it.
