### ISSUE TITLE
Question about run mha on Ubuntu 20.04,mariadb 10.3.25

### ISSUE THREAD

**Issue by tf36** [yoshinorim/mha4mysql-manager#146]
I try to do repl check
it kept says it have theses problem
i tried to connect directly through mysql -u user -p --host, and it was work

mha@monitorserver:~$ masterha_check_repl --conf /etc/mha.cnf
Thu Feb  4 14:36:48 2021 - [info] Reading default configuration from /etc/masterha_default.cnf..
Thu Feb  4 14:36:48 2021 - [info] Reading application default configuration from /etc/mha.cnf..
Thu Feb  4 14:36:48 2021 - [info] Reading server configuration from /etc/mha.cnf..
Thu Feb  4 14:36:48 2021 - [info] MHA::MasterMonitor version 0.58.
Thu Feb  4 14:36:50 2021 - [error][/usr/share/perl5/MHA/MasterMonitor.pm, ln427] Error happened on checking configurations. Redundant argument in sprintf at /usr/share/perl5/MHA/NodeUtil.pm line 195.
Thu Feb  4 14:36:50 2021 - [error][/usr/share/perl5/MHA/MasterMonitor.pm, ln525] Error happened on monitoring servers.
Thu Feb  4 14:36:50 2021 - [info] Got exit code 1 (Not master dead).

MySQL Replication Health is NOT OK!

P.S.
I found this https://code.google.com/archive/p/mysql-master-ha/issues/70,but i have no idea where that SlaveUtil.pm are.

**Comment by tf36** [comment]
sorry I found it

**Comment by hungnt1** [comment]
Can you tell me how to solve it ?
