### ISSUE TITLE
Documentation broken because of dead google code wiki

### ISSUE THREAD

**Issue by sjas** [yoshinorim/mha4mysql-manager#84]
After all of the google code hosting goes down, the hyperlinks towards the wiki pages in the source code do not work any longer.

Also there seems to be no backup possibly to be found via archive.org.

Example: bin/masterha_master_switch - there may be more. Using the URL leads to:

{"data":{"text":"Anonymous users does not have storage.objects.get access to object google-code-archive/v2/code.google.com/mysql-master-ha/wiki/Requirements.wiki."},"status":401,"config":{"method":"GET","transformRequest":[null],"url":"https://www.googleapis.com/storage/v1/b/google-code-archive/o/v2%2Fcode.google.com%2Fmysql-master-ha%2Fwiki%2FRequirements.wiki?alt=media","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""}

If just trying to access the wiki, there are no existing page anymore.

**Comment by mszel42** [comment]
you can find it here: 
https://github.com/yoshinorim/mha4mysql-manager/wiki/

**Comment by sjas** [comment]
seems this wont ever be fixed
